### PR TITLE
Use new shared styleguide, and update files to pass linting

### PR DESCRIPTION
**Pull request by hen-zone**
Sorry this is so huge. Almost every line has changed. But tests and lint both pass.

Linter has warnings which we may wish to address later (mostly JSX accessibility and indexes-as-keys).

### CODE REVIEW

**Comment by xow** [comment]
This seems okay, but I kinda want to wait till Bob is back to complete the voting on semicolons. Maybe I need to admit defeat?

I know this sucks since it will just gain more an more conflicts.

Interested in hearing your thoughts

**Comment by hen-zone** [comment]
I want to get consensus, but in the shorter term I think it's a good idea to have a shared stylesheet — and on this issue, we are deferring to the Airbnb styleguide. If we decide to change that in the future, we will be able to automatically and painlessly update everything to remove the semicolons. The only downside is that we will have another megacommit like this one.

**Comment by xow** [comment]
Good point

**Comment by hen-zone** [comment]
@xow We needed to resolve a merge conflict — could you reapprove once CI finishes?

**Pull request merged**
